chc_grupos_grupos:
    path:     /comunidad/{codigo}
    defaults: { _controller: CHCGruposBundle:Grupos:index }
    
chc_matrimonios_get:
    path:     /matrimonios/{codigo}
    methods:  [GET]
    defaults: { _controller: CHCGruposBundle:Grupos:getMatrimonios }
    
chc_matrimonios_post:
    path:     /matrimonios/{codigo}
    methods:  [POST]
    defaults: { _controller: CHCGruposBundle:Grupos:postMatrimonios }
    
chc_matrimonios_delete:
    path:     /matrimonios/{codigo}/{id}
    methods:  [DELETE]
    defaults: { _controller: CHCGruposBundle:Grupos:deleteHermanos }
    
chc_solteros_get:
    path:     /solteros/{codigo}
    methods:  [GET]
    defaults: { _controller: CHCGruposBundle:Grupos:getSolteros }
    
chc_solteros_post:
    path:     /solteros/{codigo}
    methods:  [POST]
    defaults: { _controller: CHCGruposBundle:Grupos:postSolteros }
    
chc_solteros_delete:
    path:     /solteros/{codigo}/{id}
    methods:  [DELETE]
    defaults: { _controller: CHCGruposBundle:Grupos:deleteHermanos }
    
chc_ausentes_get:
    path:     /ausentes/{codigo}
    methods:  [GET]
    defaults: { _controller: CHCGruposBundle:Grupos:getAusentes }
    
chc_ausentes_post:
    path:     /ausentes/{codigo}
    methods:  [POST]
    defaults: { _controller: CHCGruposBundle:Grupos:postAusentes }
    
chc_ausentes_delete:
    path:     /ausentes/{codigo}/{id}
    methods:  [DELETE]
    defaults: { _controller: CHCGruposBundle:Grupos:deleteHermanos }
    
chc_hermanos_put:
    path:     /hermanos/put/{codigo}/{id}
    methods:  [POST]
    defaults: { _controller: CHCGruposBundle:Grupos:putHermanos }
